defaults:
  - _exp1_bandit

trainer:
  experiment_name: bandit-generalization

es_manager:
  train:
    env_configs:
      tags: ["BanditGeneralization"] # BanditGeneralizationNoThink
  val:
    env_groups: 256
    env_configs:
      tags: ["BanditGeneralization", "BanditGeneralizationTest"]
      n_groups: [128, 128] # [128] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation