defaults:
  - critic

system:
  CUDA_VISIBLE_DEVICES: "0,1,2,3"

micro_batch_size_per_gpu: 8

actor_rollout_ref:
  rollout:
    response_length: 400
    val_kwargs:
      do_sample: True
      temperature: 0.5 # enabling randomness in evaluation 
 
trainer:
  experiment_name: bandit-base

agent_proxy:
  max_turn: 1
  max_actions_per_turn: 1 # how many actions can be output at most in a single turn

es_manager:
  format_penalty: -0.2
  train:
    env_configs:
      tags: ["Bandit"] # BanditGeneralizationNoThink
  val:
    env_configs:
      tags: ["Bandit"]
