defaults:
  - base

trainer:
  experiment_name: frozenlake-main


agent_proxy:
  max_turn: 5
  max_actions_per_turn: 10 # how many actions can be output at most in a single turn

es_manager:
  train:
    env_configs:
      tags: ["FrozenLake"]
  val:
    env_configs:
      tags: ["FrozenLake"]
