defaults:
  - base # this is a symbolic link to the verl/verl/trainer/config/ppo_trainer.yaml file

es_manager:
  format_penalty: -1.0
  group_size: ${agent_proxy.rollout_n}
  train:
    env_groups: ${data.env_groups} 
    # under the same group, the env config and env seed are ensured to be equal
    group_size: ${es_manager.group_size}
    env_configs:
      tags: ["Bandit"]
      n_groups: [8] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
  val:
    env_groups: ${data.val_batch_size}
    group_size: 1 # should be set to 1 because val temperature is set to 0 and same prompt leads to same output
    env_configs:
      tags: ["Bandit"]
      n_groups: [128] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation