defaults:
  - _exp1_bandit

system:
  CUDA_VISIBLE_DEVICES: "1"

trainer:
  project_name: ragen_new
  experiment_name: bandit-generalization-nothink

agent_proxy:
  enable_think: False # False -> no think RL

es_manager:
  format_penalty: -0.1
  train:
    env_groups: 8
    # under the same group, the env config and env seed are ensured to be equal
    group_size: 16
    env_configs:
      tags: ["BanditGeneralizationNothink"] # BanditGeneralizationNoThink
      n_groups: [8] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
  val:
    env_groups: 256
    group_size: 1 # should be set to 1 because val temperature is set to 0 and same prompt leads to same output
    env_configs:
      tags: ["BanditGeneralizationNothink", "BanditGeneralizationNothinkTest"]
      n_groups: [128, 128] # [128] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation