defaults:
  - base # this is a symbolic link to the verl/verl/trainer/config/ppo_trainer.yaml file

actor_rollout_ref:
  actor:
    ppo_mini_batch_size: 32
    micro_batch_size_per_gpu: 32
    ppo_micro_batch_size_per_gpu: 32
  ref:
    log_prob_micro_batch_size_per_gpu: 32
  rollout:
    log_prob_micro_batch_size_per_gpu: 32
    tensor_model_parallel_size: 1
    max_model_len: 2048
    response_length: 200 # single-turn response length

critic:
  ppo_mini_batch_size: 32
  ppo_micro_batch_size_per_gpu: 32

trainer:
  n_gpus_per_node: 1
