defaults:
  - ppo_trainer # this is a symbolic link to the verl/verl/trainer/config/ppo_trainer.yaml file

actor_rollout_ref:
  model:
    path: Qwen/Qwen2.5-0.5B-Instruct
  actor:
    ppo_mini_batch_size: 32
    micro_batch_size_per_gpu: 1
    ppo_micro_batch_size_per_gpu: 1
  ref:
    log_prob_micro_batch_size_per_gpu: 1
  rollout:
    log_prob_micro_batch_size_per_gpu: 1

critic:
  ppo_micro_batch_size_per_gpu: 1

data:
  train_batch_size: 4 # 128
  val_batch_size: 4 # 128
  env_groups: 2 # 8
  rollout_n: ${int_div:${data.train_batch_size}, ${data.env_groups}} # NOTE: need to check. equals batch_size / env_groups, different from "n", because this rollout_n determines the number of envs in the same group

trainer:
  total_training_steps: 200
  validation_steps: 1 # validation instances = validation_steps * val_batch_size
  val_before_train: True

logging:
  log_images: True
  log_image_dir: log/trajectory
  log_image_step_size: 1
  log_n_image_per_batch: 4
  log_n_sample_per_batch: 1

agent_proxy:
  max_turn: 5
  rollout_n: ${data.rollout_n}
  action_sep: " || "

es_manager:
  format_penalty: -1.0
  group_size: ${agent_proxy.rollout_n}
  train:
    env_groups: ${data.env_groups} 
    # under the same group, the env config and env seed are ensured to be equal
    group_size: ${es_manager.group_size}
    env_configs:
      tags: ["SimpleSokoban", "HarderSokoban"]
      n_groups: [1, 1] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
  val:
    env_groups: ${data.env_groups}
    group_size: ${es_manager.group_size}
    env_configs:
      tags: ["SimpleSokoban"]
      n_groups: [2] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation

ctx_manager:
  generation: # go to vllm
    gen_config:
      top_p: 1
      temperature: 1
      kwargs: null

custom_envs:
  SimpleSokoban:
    env_type: sokoban
    str_to_action_lookup:
      up: 1
      down: 2
      left: 3
      right: 4
    env_instruction: "You are solving the Simple Sokoban puzzle."
    env_config: # keys should be a subset of SokobanConfig
      dim_x: 6
      dim_y: 6
      num_boxes: 1
      max_steps: 100

  HarderSokoban:
    env_type: sokoban
    str_to_action_lookup:
      up: 1
      down: 2
      left: 3
      right: 4
    env_instruction: "You are solving the Harder Sokoban puzzle."
    env_config:
      dim_x: 10
      dim_y: 10
      num_boxes: 2
      max_steps: 100





