defaults:
  - ppo_trainer # this is a symbolic link to the verl/verl/trainer/config/ppo_trainer.yaml file

actor_rollout_ref:
  model:
    path: Qwen/Qwen2.5-0.5B-Instruct

data:
  train_batch_size: 8
  rollout_n: 16



logging:
  log_images: True
  log_image_dir: log/trajectory
  log_image_step_size: 1
  log_n_image_per_batch: 4
  log_n_sample_per_batch: 1

agent_proxy:
  max_turn: 5
  rollout_n: ${data.rollout_n}
  action_sep: " || "
  es_manager:
    train:
      env_groups: ${data.train_batch_size} 
      # under the same group, the env config and env seed are ensured to be equal
      group_size: ${agent_proxy.rollout_n}
      env_configs:
        Tags: ["SimpleSokoban", "HarderSokoban"]
        n_groups: [6, 2] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
    val:
      env_groups: ${data.train_batch_size}
      group_size: ${agent_proxy.rollout_n}
      env_configs:
        Tags: ["SimpleSokoban"]
        n_groups: [8] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation

  ctx_manager:
    generation: # go to vllm
      gen_config:
        top_p: 1
        temperature: 1
        kwargs: null

custom_envs:
  Simplesokoban:
    env_type: sokoban
    env_instruction: "You are a helpful assistant that can solve the Simple Sokoban puzzle."
    env_config: # keys should be a subset of SokobanConfig
      dim_x: 6
      dim_y: 6
      kwargs: {}

  Hardersokoban:
    n_group: 2
    env_type: sokoban
    env_instruction: "You are a helpful assistant that can solve the Harder Sokoban puzzle."
    env_config:
      dim_x: 10
      dim_y: 10





