defaults:
  - base

actor_rollout_ref:
  actor:
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: grpo # gae means critic and grpo means no critic
  kl_penalty: low_var_kl  # how to estimate kl divergence
  kl_ctrl:
    type: fixed
    kl_coef: 0.001