defaults:
  - base # this is a symbolic link to the verl/verl/trainer/config/ppo_trainer.yaml file

system:
  CUDA_VISIBLE_DEVICES: "0,1,2,3"

actor_rollout_ref:
  actor:
    ppo_mini_batch_size: null # by default, ppo_mini_batch_size = train_batch_size / 4
    micro_batch_size_per_gpu: null # by default, no grad accumulation
    ppo_micro_batch_size_per_gpu: null # by default, no grad accumulation
  ref:
    log_prob_micro_batch_size_per_gpu: null # by default, no grad accumulation
  rollout:
    log_prob_micro_batch_size_per_gpu: null # by default, no grad accumulation
    tensor_model_parallel_size: 2

critic:
  ppo_mini_batch_size: null # by default, ppo_mini_batch_size = train_batch_size / 4
  ppo_micro_batch_size_per_gpu: null # by default, no grad accumulation

trainer:
  n_gpus_per_node: 4
  project_name: ragen_new
  experiment_name: test-0.5B-frozenlake-removeinvalid

agent_proxy:
  reward_normalization:
    grouping: "env" # env / batch / prompt
    method: "mean_std"

es_manager:
  format_penalty: -1.0
  train:
    env_groups: 8
    # under the same group, the env config and env seed are ensured to be equal
    group_size: 16
    env_configs:
      tags: ["FrozenLake"] #, "Bandit", "Countdown"]
      n_groups: [8] #, 8, 8] # If not set, all env names int_divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
  val:
    env_groups: 128
    group_size: 1 # should be set to 1 because val temperature is set to 0 and same prompt leads to same output
    env_configs:
      tags: ["FrozenLake"] #, "Bandit", "Countdown"]
      n_groups: [128] #, 128, 128] # If not set, all env names int_divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation

