defaults:
  - base # this is a symbolic link to the verl/verl/trainer/config/ppo_trainer.yaml file

system:
  CUDA_VISIBLE_DEVICES: "0,1,2,3"

trainer:
  project_name: ragen_new
  experiment_name: Qwen/Qwen2.5-3B-Instruct

actor_rollout_ref:
  model:
    path: Qwen/Qwen2.5-3B-Instruct

    
es_manager:
  train:
    env_groups: 8
    # under the same group, the env config and env seed are ensured to be equal
    group_size: 16
    env_configs:
      tags: ["MetamathQA"] # ["Bandit"]  ["Countdown"] ["FrozenLake"] ["SimpleSokoban"]
      n_groups: [8] #, 8, 8] # If not set, all env names int_divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation
  val:
    env_groups: 128
    group_size: 1 # should be set to 1 because val temperature is set to 0 and same prompt leads to same output
    env_configs:
      tags: ["MetamathQA"] #, "Countdown"]
      n_groups: [128] #, 128, 128] # If not set, all env names int_divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation

